### ISSUE TITLE
Improve swagger.json and docs page types

### ISSUE THREAD

**Issue by alber70g** [kadena-io/signing-api#20]
Currently the docs are showing types with examples.

```
// e.g. https://kadena-io.github.io/signing-api/#/definitions/QuickSignRequest
sigs: object 
  acbe76b30ccaf57e269a0cd5eeeb7293e7e84c7d68e6244a64c4adf4d2df6ea1: string 
  // this should not be the key
```

The swagger would be this
```yaml
sigs:
  description: 'dictionary of public-key - signature'
  additionalProperties:
    type: string
```

instead of

```yaml
sigs:
  required:
    - acbe76b30ccaf57e269a0cd5eeeb7293e7e84c7d68e6244a64c4adf4d2df6ea1
  type: object
  properties:
    acbe76b30ccaf57e269a0cd5eeeb7293e7e84c7d68e6244a64c4adf4d2df6ea1:
      type: 'null'
            
```
